"""add profile fields and relationships

Revision ID: 06854bda6d93
Revises: d6023d8650a3
Create Date: 2025-10-19 00:20:37.340149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06854bda6d93'
down_revision: Union[str, Sequence[str], None] = 'd6023d8650a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'created_at')
    # ### end Alembic commands ###
