"""fixed user delete

Revision ID: 467651c074a8
Revises: f4a896af13f3
Create Date: 2025-10-18 23:37:21.611348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467651c074a8'
down_revision: Union[str, Sequence[str], None] = 'f4a896af13f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('followers_followed_id_fkey'), 'followers', type_='foreignkey')
    op.drop_constraint(op.f('followers_follower_id_fkey'), 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['followed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(op.f('followers_follower_id_fkey'), 'followers', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(op.f('followers_followed_id_fkey'), 'followers', 'users', ['followed_id'], ['id'])
    # ### end Alembic commands ###
